### ISSUE TITLE
Env!

### ISSUE THREAD

**Issue by BlackIQ** [f-mohrechi/react-auth0#1]
Add .env in .gitignore file to be ignored.

create a .env.example the includes just variables without values. Like:

API_ENDPOINT=

—-

Wish you luck.

**Comment by f-mohrechi** [comment]
Thanks for letting me know that.
It was already in .gitignore, but I'm not sure why it was still showing up.

**Comment by BlackIQ** [comment]
You had this file before adding it go .gitignore. To solve:
First delete the .env file. Then commit it with any comment. Then any .env file will be ignored.

Tell me if you had any problem.

**Comment by f-mohrechi** [comment]
"I think it's working properly now."

**Comment by BlackIQ** [comment]
If you did it, can we close the issue?

**Comment by f-mohrechi** [comment]
yes
